# Generated by Django 5.1.6 on 2025-03-03 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samdukfdoc',
            name='samdukf',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samdukfdoc', to='main.samdukf'),
        ),
    ]
